### PR TITLE
[Feature] title animation

### PR DESCRIPTION
**Pull request by LofiSu**
Implemented animation effect where 'AI Gateway' appears first, followed by the expansion into 'AI Native API Gateway' with a typewriter effect.

### CODE REVIEW

**Comment by LofiSu** [comment]
I accidentally deleted the source code when I cleaned up the file at noon, and then directly pulled the local main branch. I don't know if the title animation written by the code written in the morning is completely saved, so I resubmitted the pr of the title animation.

**Comment by LofiSu** [comment]
https://github.com/user-attachments/assets/b6f9ef8a-d35e-4963-a8d2-73fe23b0eedd

**Review by LofiSu — COMMENTED** [review]
I deleted the animation of the AI gateway.

**Review by LofiSu — COMMENTED** [review]
English shows AI Gateway and AI Native API Gateway.

**Review by johnlanni — APPROVED** [review]
LGTM

**Pull request merged**
